# Generated by Django 5.0.6 on 2024-06-16 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('quest_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_area', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('available', models.BooleanField()),
                ('password', models.CharField(max_length=100)),
                ('quest_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField()),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'quest_id')},
            },
        ),
    ]
