# Generated by Django 5.0.6 on 2024-07-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_quest',
            name='completion_date',
            field=models.CharField(max_length=50),
        ),
    ]
